# This file was generated by GoReleaser. DO NOT EDIT.
class Engarde < Formula
  desc "Engarde - Stay on guard with Envoy Access Logs"
  homepage "https://github.com/kushthedude/engarde"
  version "0.1.1"

  if OS.mac?
    url "https://github.com/nitishm/engarde/releases/download/v0.1.1/engarde_0.1.1_Darwin_x86_64.zip"
    sha256 "d927157b3585c178fc085125d411c85790ba769acb7f5f2cefd4d28a9093a6f5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nitishm/engarde/releases/download/v0.1.1/engarde_0.1.1_Linux_x86_64.zip"
      sha256 "5d242484169656ef92e50c4d64c4d902360733fa0ce4620e7da154bd7c02ddd4"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nitishm/engarde/releases/download/v0.1.1/engarde_0.1.1_Linux_arm64.zip"
        sha256 "af5e2289dd9d4857990caecf1949a4994b663056118e56c01b946be32739cc72"
      else
        url "https://github.com/nitishm/engarde/releases/download/v0.1.1/engarde_0.1.1_Linux_armv6.zip"
        sha256 "985cff7a4502e1a2a4d632df3e0cbe4008fc9bcae769640cb4f45231a97addce"
      end
    end
  end

  def install
    bin.install "engarde"
  end
end
